### ISSUE TITLE
Callback objects garbage collected

### ISSUE THREAD

**Issue by xkr47** [jaudiolibs/jnajack#12]
First, thanks for a great library!

With 1.4.0 I am occasionally getting these messages in the console:

```
JNA: callback object has been garbage collected
JNA: callback object has been garbage collected
JNA: callback object has been garbage collected
```

Sometimes within maybe 10 seconds of, sometimes 10 minutes after startup, and sometimes it works fine for ages. I have also tried to enforce GC with `System.gc()` but that doesn't seem to trigger it.

The symptoms are that callbacks are no longer being called (none of them) and the message repeats apparently whenever there would have been a call to a callback..

I am running java version "1.8.0_144".

My client does not stream any audio or other data, it acts like a patchbay app that makes sure connections are the way I want them all the time, so there can be long intervals when there are no events being processed.

**Comment by neilcsmith-net** [comment]
Which callback? Are you sure your client can't be GC'd? Can you share some of the code to reproduce? 

Thanks for the thanks :smile:

**Comment by xkr47** [comment]
I'm not sure, but I guess usually in Java if you register a listener, that listener is the reference that keeps the app from GCing..

Here's the code: https://github.com/xkr47/jacktools/blob/master/src/main/java/space/xkr47/jacktools/Patchbay.java

Yeah some functions are a bit messed up, I was trying some different approaches on state management and I haven't cleaned it up..

**Comment by neilcsmith-net** [comment]
Thanks!  I can't think of many things off the top of my head where the listener / callback has a reference to what it's registered on.  With JNA in general you need to keep a hard reference to callbacks so they don't get GC'd - the GC has no understanding of native references.  In JNAJack, the JackClient does keep a reference to every callback for you, but you have to ensure the client doesn't get collected.  This is usually fine in normal usage as you need to keep a reference to clean up the client when done / before exiting.

So, you're keeping a reference to the client, but it's still being collected - partly because you don't clean up.  I think you're hitting one of the weird intricacies of working with Java and native code - your Patchbay instance is being GC'd because the loop code can be inlined.  Try putting the Patchbay you create in main into a static final field and see if that fixes the issue.

If you want to learn some "fun" stuff related to this, check out https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Reference.html#reachabilityFence(java.lang.Object) and some of the discussion about why it was added in Java 9! :wink:

**Comment by xkr47** [comment]
Ok thanks a lot! I will try your suggestions and read the docs. One thing I just recalled is that my main exits after startup. It starts a threadpool with a single thread but that of course has no reference to my code unless I have something scheduled; which I don't, most of the time. Perhaps another idea would be to store a reference to `Patchbay` in a threadlocal of the threadpool thread :grin: Wait no, the threadlocal instance probably will get GC:d just as well..
